name: url-app
services:
  db:
    image: "postgres:14-alpine"
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=DB_Urls2
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"

  url-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/DB_Urls2'
      SPRING_DATASOURCE_USERNAME: 'admin'
      SPRING_DATASOURCE_PASSWORD: 'admin'
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'
      JAVA_OPTS: >-
        -XX:+UseZGC
        -Xms256M
        -Xmx2G
      SPRING_PROFILES_ACTIVE: "local"
    ports:
      - "8080:8080"
    depends_on:
      - db