spring:
  application:
    name: url-app
  datasource:
    url: jdbc:postgresql://localhost:5433/DB_Urls2
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    sql: INFO